#!/usr/bin/env bash

if [ $# = 0 ]; then
  TERM=xterm-256color ssh trickfire@192.168.0.146
else
  ~/Code/Robotics/urc-2023/sync_to_orin.sh 192.168.0.146 /home/trickfire/urc-2023
  TERM=xterm-256color ssh trickfire@192.168.0.146
fi
